language: python
python: 2.7

# Use container-based infrastructure
sudo: false

install:
  - pip install requests
  - pip install tox

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=docs
